<footer id="footerVisitor">
    <nav class="footer-links">
        <h3>Informations légales</h3>
        <ul class="legal">
            <li><a href="#">Mentions légales</a></li>
            <li><a href="#">FAQ</a></li>
        </ul>
    </nav>
    <nav class="footer-menu">
        <h3>Nos services</h3>
        <ul class="menu">
            <li><a href="/projet-final-v2/services">Services</a></li>
            <li><a href="/projet-final-v2/homepage">Nous trouver</a></li>
        </ul>
    </nav>
    <nav class="footer-social">
        <h3>Suivez-nous</h3>
        <ul class="social">
             <li><a href="https://facebook.com/" target="_blank"><i class="fab fa-facebook facebook-icon" title="lien facebook"></i></a></li>
             <li><a href="https://instagram.com/" target="_blank"><i class="fab fa-instagram instagram-icon" title="lien instagram"></i></a></li>
             <li><a href="https://twitter.com/" target="_blank"><i class="fa-brands fa-square-x-twitter twitter-icon" title="lien twitter"></i></a></li>
        </ul>
    </nav>
    <div class="copyright">
        <p>&copy; <?php echo date("Y"); ?> Guillaume Tessier. Tous droits réservés. </p>
    </div>
</footer>
