

<footer id="footerAdmin">
    <nav class="footer-links">
        <h3>Informations légales</h3>
        <ul class="legal">
            <li><a href="#">Mentions légales</a></li>
            <li><a href="#">FAQ</a></li>
        </ul>
    </nav>
    <nav class="footer-menu">
        <h3>Administration du Site</h3>
        <ul class="menu">
             <li><a href="/projet-final-v2/administrer" title="Gérer les utilisateurs">Gérer les utilisateurs</a></li>
            <li><a href="/projet-final-v2/messages" title="Gérer les messages">Gérer les messages</a></li>
            <li><a href="/projet-final-v2/calendar_admin" title="Calendrier-planing">Gérer les rendez-vous</a></li>
        </ul>
    </nav>
    <nav class="footer-social">
        <h3>Mes réseaux</h3>
        <ul class="social">
             <li><a href="https://facebook.com/" target="_blank"><i class="fab fa-facebook facebook-icon" title="lien facebook"></i></a></li>
             <li><a href="https://instagram.com/" target="_blank"><i class="fab fa-instagram instagram-icon" title="lien instagram"></i></a></li>
             <li><a href="https://twitter.com/" target="_blank"><i class="fa-brands fa-square-x-twitter twitter-icon" title="lien twitter"></i></a></li>
        </ul>
    </nav>
    <div class="copyright">
        <p>&copy; <?php echo date("Y"); ?> Guillaume Tessier. Tous droits réservés. </p>
    </div>
</footer>

