<!--contenue de mon footer / faq /lien réseaux sociaux/ liens vers pages menu/ politique de sécurité/-->

<footer id="footer">
    <div class="footer-links">
        <ul class="legal">
            <li><a href="#">Mentions légales</a></li>
            <li><a href="#">FAQ</a></li>
        </ul>
    </div>
    <div class="footer-menu">
        <ul class="menu">
            <li><a href="#">Services</a></li>
            <li><a href="#">Rendez-vous</a></li>
            <li><a href="#">Contact</a></li>
        </ul>
    </div>
    <div class="footer-social">
        <ul class="social">
            <li><a href="#"><i class="fab fa-instagram"></i></a></li>
            <li><a href="#"><i class="fab fa-facebook"></i></a></li>
            <li><a href="#"><i class="fab fa-linkedin"></i></a></li>
        </ul>
    </div>
</footer>
