<header id="headerUser">
   
   <nav class="navbar-mobile">
     <i class="fas fa-bars"></i>   
      <div class="modal">     

    <ul class="navbar-mobile-list">
        <li><a href="/projet-final-v2/homepage"> Accueil</a></li>
        <li><a href="/projet-final-v2/update_profile">Mon profil</a></li>
        <li><a href="/projet-final-v2/services">Services</a></li>
        <li><a href="/projet-final-v2/create_message">Messages</a></li>
        <li><a href="/projet-final-v2/create_appointment">Rendez-vous</a></li>
        <li><a href="/projet-final-v2/calendar_user">Calendrier</a></li>
        <li><a href="/projet-final-v2/connexion">Déconnexion</a></li>
        <div class="social-icons-mobile">
        <li><a href="https://twitter.com/" target="_blank"><i class="fa-brands fa-square-x-twitter twitter-icon"></i></a></li>
        <li><a href="https://facebook.com/" target="_blank"><i class="fab fa-facebook facebook-icon"></i></a></li>
        <li><a href="https://instagram.com/" target="_blank"><i class="fab fa-instagram instagram-icon"></i></a></li>
      </div>
</div>
    </ul>
       </div>   
</nav>
<nav>
    <!-- Menu pour l'utilisateur connecté -->
    <ul class="navbar-desktop">
        <li><a href="/projet-final-v2/homepage"> Accueil</a></li>
        <li><a href="/projet-final-v2/update_profile">Mon profil</a></li>
        <li><a href="/projet-final-v2/services">Services</a></li>
        <li><a href="/projet-final-v2/create_message">Messages</a></li>
        <li><a href="/projet-final-v2/create_appointment">Rendez-vous</a></li>
        <li><a href="/projet-final-v2/calendar_user">Calendrier</a></li>
        <li><a href="/projet-final-v2/connexion">Déconnexion</a></li>
        <li><a href="https://twitter.com/" target="_blank"><i class="fa-brands fa-square-x-twitter twitter-icon"></i></a></li>
        <li><a href="https://facebook.com/" target="_blank"><i class="fab fa-facebook facebook-icon"></i></a></li>
        <li><a href="https://instagram.com/" target="_blank"><i class="fab fa-instagram instagram-icon"></i></a></li>
    </ul>
</nav>
</header>

<script type="text/javascript" src="assets/js/header.js"></script>