<header id="headerVisitor">
   
   <nav class="navbar-mobile"> 
   <div class="logo">
         <a href="/projet-final-v2/accueil" title="Accédez à la page d'accueil">
             <span class="drive">Drive</span>
             <span class="safe">Safe</span>
             <span class="control">Control</span>
         </a>
     </div>
     <i class="fas fa-bars"></i>   
      <div class="modal"> 
      

    <ul class="navbar-mobile-list">
        <li class="logo"><a href="/projet-final-v2/accueil" title="Accédez à la page d'accueil"><span class="drive">Drive</span><span class="safe" >Safe</span><span class="control">Control</span></a></li>
        <li><a href="/projet-final-v2/connexion">Connexion</a></li>
        <li><a href="/projet-final-v2/services" title="Nos services">Prestations</a></li>
         <li><a href="/projet-final-v2/créer-un-compte">Inscription</a></li>
      <div class="social-icons-mobile">
        <li><a href="https://twitter.com/" target="_blank"><i class="fa-brands fa-square-x-twitter twitter-icon" title="lien twitter"></i></a></li>
        <li><a href="https://facebook.com/" target="_blank"><i class="fab fa-facebook facebook-icon" title="lien facebook"></i></a></li>
        <li><a href="https://instagram.com/" target="_blank"><i class="fab fa-instagram instagram-icon" title="lien instagram"></i></a></li>
      </div>
       
</ul> 
</div>
    
       
</nav>
<nav class="navbar-desktop">
   
    <ul >
        <li class="logo" >
            <a href="/projet-final-v2/accueil" title="Accédez à la page d'accueil" ><span class="drive">Drive</span><span class="safe" >Safe</span><span class="control">Control</span></a>
            </li>
               <li><a href="/projet-final-v2/connexion">Connexion</a></li>
               <li><a href="/projet-final-v2/créer-un-compte">Inscription</a></li>
               <li><a href="/projet-final-v2/services" title="Nos services">Prestations</a></li>
        <div class="social-icons-desktop">
               <li><a href="https://twitter.com/" target="_blank"><i class="fa-brands fa-square-x-twitter twitter-icon" title="lien twitter"></i></a></li>
               <li><a href="https://facebook.com/" target="_blank"><i class="fab fa-facebook facebook-icon" title="lien facebook"></i></a></li>
               <li><a href="https://instagram.com/" target="_blank"><i class="fab fa-instagram instagram-icon" title="lien instagram"></i></a></li>
        </div>
        <div class="indicator"></div> 
    </ul>
</nav>
</header>

<script type="text/javascript" src="assets/js/header.js"></script>