<header id="headerAdmin">
   
    <nav class="navbar-mobile">
        <i class="fas fa-bars"></i>
        <div class="modal">
            <ul class="navbar-mobile-list">
                <li class="logo"><a href="/projet-final-v2/homepage" title="Accédez à la page d'accueil"><span class="drive">Drive</span><span class="safe">Safe</span><span class="control">Control</span></a></li>
                <li><a href="/projet-final-v2/administrer" title="Gérer les utilisateurs">Gérer les utilisateurs</a></li>
                <li><a href="/projet-final-v2/messages" title="Gérer les messages">Gérer les messages</a></li>
                <li><a href="/projet-final-v2/calendar_admin" title="Calendrier-planing">Calendrier-planing</a></li>
                <div class="social-icons-mobile">
                    <li><a href="https://twitter.com/" target="_blank"><i class="fa-brands fa-square-x-twitter twitter-icon" title="lien twitter"></i></a></li>
                    <li><a href="https://facebook.com/" target="_blank"><i class="fab fa-facebook facebook-icon" title="lien facebook"></i></a></li>
                    <li><a href="https://instagram.com/" target="_blank"><i class="fab fa-instagram instagram-icon" title="lien instagram"></i></a></li>
                </div>
                <li><a href="/projet-final-v2/deconnexion"><i class="fa-solid fa-right-from-bracket" title="Se déconnecter"></i></a></li>
            </ul>
        </div>
    </nav>
   
    <nav class="navbar-desktop">
        <ul>
            <li class="logo"><a href="/projet-final-v2/homepage" title="Accédez à la page d'accueil"><span class="drive">Drive</span><span class="safe">Safe</span><span class="control">Control</span></a></li>
            <li><a href="/projet-final-v2/administrer" title="Gérer les utilisateurs">Gérer les utilisateurs</a></li>
            <li><a href="/projet-final-v2/messages" title="Gérer les messages">Gérer les messages</a></li>
            <li><a href="/projet-final-v2/calendar_admin" title="Calendrier-planing">Calendrier-planing</a></li>
            <li><a href="https://twitter.com/" target="_blank"><i class="fa-brands fa-square-x-twitter twitter-icon" title="lien twitter"></i></a></li>
            <li><a href="https://facebook.com/" target="_blank"><i class="fab fa-facebook facebook-icon" title="lien facebook"></i></a></li>
            <li><a href="https://instagram.com/" target="_blank"><i class="fab fa-instagram instagram-icon" title="lien instagram"></i></a></li>
            <li><a href="/projet-final-v2/deconnexion"><i class="fa-solid fa-right-from-bracket" title="Se déconnecter"></i></a></li>
            <div class="indicator"></div> 
        </ul>
    </nav>
</header>

<script type="text/javascript" src="assets/js/header.js"></script>
