<!-- Menu pour l'administrateur -->
<h1>Dashboard Admin</h1>
<nav class="admin-navbar">
    <ul>
        <li><a href="index.php?route=homepage">Retour accueil</a></li>
        <li><a href="index.php?route=users">Gérer les utilisateurs</a></li>
        <li><a href="index.php?route=messages">Gérer les messages</a></li>
        <li><a href="index.php?route=index_appointment">Gestion des rendez-vous</a></li>
        <li><a href="index.php?route=calendar_admin">calendrier-planing</a></li>
        <li><a href="index.php?route=logout">deconnexion</a></li>
        <!-- Ajoutez d'autres liens si nécessaire -->
    </ul>
</nav>