<header id="header-visitor">
   <!-- Bouton hamburger -->
  <div class="hamburger">☰</div>

<nav class="menu">
  
  <!-- Menu pour les visiteurs -->
    <ul>
        <li><a href="/projet-final-v2/accueil">Accueil</a></li>
        <li><a href="/projet-final-v2/services">Services</a></li>
        <li><a href="/projet-final-v2/connexion">Connexion</a></li>
        <li><a href="/projet-final-v2/créer-un-compte">Inscription</a></li>
    </ul>
</nav>
</header>
<script type="text/javascript" src="assets/js/"></script>