<!--<header id="header-visitor">-->
   <!-- Bouton hamburger -->
<!--  <div class="hamburger">☰</div>-->

<!--<nav class="menu">-->
  
  <!-- Menu pour les visiteurs -->
<!--    <ul>-->
<!--        <li><a href="/projet-final-v2/accueil">Accueil</a></li>-->
<!--        <li><a href="/projet-final-v2/services">Services</a></li>-->
<!--        <li><a href="/projet-final-v2/connexion">Connexion</a></li>-->
<!--        <li><a href="/projet-final-v2/créer-un-compte">Inscription</a></li>-->
<!--    </ul>-->
<!--</nav>-->
<!--</header>-->
<!--<script type="text/javascript" src="assets/js/header.js"></script>-->


<header id="headerVisitor">
   
   <nav class="navbar-mobile">
     <i class="fas fa-bars"></i>   
      <div class="modal"> 
      

    <ul class="navbar-mobile-list">
        <li class="logo"><a href="/projet-final-v2/homepage" title="Accédez à la page d'accueil"><span class="drive">Drive</span><span class="safe" >Safe</span><span class="control">Control</span></a></li>
        <li><a href="/projet-final-v2/connexion">Connexion</a></li>
        <li><a href="/projet-final-v2/services" title="Nos services">Services</a></li>
        <!--<li><a href="/projet-final-v2/create_appointment" title="Prendre rendez-vous">Rendez-vous</a></li>-->
         <li><a href="/projet-final-v2/créer-un-compte">Inscription</a></li>
      
        <div class="social-icons-mobile">
        <li><a href="https://twitter.com/" target="_blank"><i class="fa-brands fa-square-x-twitter twitter-icon" title="lien twitter"></i></a></li>
        <li><a href="https://facebook.com/" target="_blank"><i class="fab fa-facebook facebook-icon" title="lien facebook"></i></a></li>
        <li><a href="https://instagram.com/" target="_blank"><i class="fab fa-instagram instagram-icon" title="lien instagram"></i></a></li>
      </div>
       
</ul> 
</div>
    
       
</nav>
<nav class="navbar-desktop">
    <!-- Menu pour l'utilisateur connecté -->
    <ul >
        <li class="logo" >
            <a href="/projet-final-v2/homepage" title="Accédez à la page d'accueil" ><span class="drive">Drive</span><span class="safe" >Safe</span><span class="control">Control</span></a>
            </li>
               <li><a href="/projet-final-v2/connexion">Connexion</a></li>

        <li><a href="/projet-final-v2/services" title="Nos services">Services</a></li>
        <li><a href="/projet-final-v2/create_message" title="Nous contacter">Contact</a></li>
        <!--<li><a href="/projet-final-v2/create_appointment" title="Prendre rendez-vous">Rendez-vous</a></li>-->
       
         <li><a href="https://twitter.com/" target="_blank"><i class="fa-brands fa-square-x-twitter twitter-icon" title="lien twitter"></i></a></li>
        <li><a href="https://facebook.com/" target="_blank"><i class="fab fa-facebook facebook-icon" title="lien facebook"></i></a></li>
        <li><a href="https://instagram.com/" target="_blank"><i class="fab fa-instagram instagram-icon" title="lien instagram"></i></a></li>
        
        <div class="indicator"></div> 
    </ul>
</nav>
</header>

<script type="text/javascript" src="assets/js/header.js"></script>