<!-- Menu pour l'administrateur -->
<h1>Dashboard Admin</h1>
<nav class="admin-navbar">
    <ul>
        <li><a href="accueil">Retour accueil</a></li>
        <li><a href="/projet-final-v2/administrer">Gérer les utilisateurs</a></li>
        <li><a href="/projet-final-v2/messages">Gérer les messages</a></li>
        <li><a href="/projet-final-v2/appointment">Gestion des rendez-vous</a></li>
        <li><a href="/projet-final-v2/calendar_admin">calendrier-planing</a></li>
        <li><a href="/projet-final-v2/connexion">deconnexion</a></li>
        <!-- Ajoutez d'autres liens si nécessaire -->
    </ul>
</nav>