

<main id="services">
    <table class="container">
        <thead>
            <tr>
                <th></th>
                <th><h2>Type de Service Proposé</h2></th>
                <th><h2>Prix en €</h2></th>
                <th><h2>Type de Véhicule</h2></th>
<?php if (isset($_SESSION['role']) && $_SESSION['role'] === 'admin'): ?>
                    <th><h2>Actions</h2></th>
                <?php endif; ?>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($services as $service): ?>
                <tr>
                    <td><?= $service['Service_ID'] ?></td>
                    <td><?= $service['Service_name'] ?></td>
                    <td><?= $service['Service_cost'] ?></td>
                    <td><?= $service['Vehicle_type'] ?></td>
<?php if (isset($_SESSION['role']) && $_SESSION['role'] === 'admin'): ?>
                        <td>
                            <form action="/projet-final-v2/update_services" method="post">
                                <input type="hidden" name="Service_ID" value="<?= $service['Service_ID'] ?>">
                                <label for="Service_name">Nom:</label>
                                <input type="text" name="Service_name" value="<?= $service['Service_name'] ?>">
                                <label for="Service_cost">Prix:</label>
                                <input type="number" name="Service_cost" value="<?= $service['Service_cost'] ?>">
                                <label for="Vehicle_type">Type de Véhicule:</label>
                                <input type="text" name="Vehicle_type" value="<?= $service['Vehicle_type'] ?>">
                                <button type="submit">Mettre à jour</button>
                            </form>
                        </td>
                    <?php endif; ?>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</main>
