<h1>Géstion des rendez-vous</h1>
<ul>
    <?php foreach ($appointments as $appointment) : ?>
        <li>
            <a href="index.php?route=show_appointment&id=<?= $appointment->getAppointmentId() ?>">
                Rendez-vous du <?= $appointment->getAppointmentDatetime() ?>
            </a>
        </li>
    <?php endforeach; ?>
</ul>
<a href="index.php?route=create_appointment">Create New Appointment</a>