<main id="legalNotice">
    <section class=container-legal-notice>
     <h1>Mentions Légales</h1>

    <h2>Informations légales</h2>
    <h3>Identification de l'entreprise</h3>
    <ul>
        <li>Nom de l'entreprise : DriveSafeControl</li>
        <li>Forme juridique :  Société à responsabilité limitée</li>
        <li>Adresse du siège social : Za le Pont Mahaud, 5b rue du pond Mahaud, 35131 Pont-Péan</li>
        <li>Téléphone : 0290014415</li>
        <li>E-mail : email.faux.com</li>
        <li>SIRET : 913068961</li>
        <li>Numéro d'immatriculation : 913068961]</li>
        <li>Capital social : 100 000 €</li>
        <li>Directeur de la publication : Kévin Durant</li>
    </ul>

    <h2>Hébergement du site</h2>
    <ul>
        <li>Nom de l'hébergeur : Kévin Duran</li>
        <li>Adresse de l'hébergeur : 8 rue du rond point qui tourne, 35000 Rennes</li>
        <li>Numéro de téléphone de l'hébergeur :  0290014415</li>
    </ul>

    <h2>Propriété intellectuelle</h2>
    <p>Le contenu de ce site, y compris les images, graphiques, textes, vidéos, animations, sons, logos, gifs et icônes, ainsi que leur mise en forme, sont la propriété exclusive de [Votre nom d'entreprise] à l'exception des marques, logos ou contenus appartenant à d'autres sociétés partenaires ou auteurs.</p>

    <h2>Protection des données personnelles</h2>
    <p>DriveSafeControl s'engage à ce que la collecte et le traitement de vos données soient conformes au RGPD et à la loi Informatique et Libertés.</p>

    <h2>Cookies</h2>
    <p>Ce site utilise des cookies pour améliorer votre expérience utilisateur. En utilisant notre site web, vous acceptez tous les cookies conformément à notre Politique de cookies.</p>

    <h2>Limitation de responsabilité</h2>
    <p>DriveSafeControl ne pourra être tenu responsable pour des problèmes techniques tels que des erreurs, des inexactitudes, des interruptions de services, etc.</p>
</section>
    
</main>