<main id="createMessage">
<?php
if (isset($_SESSION['confirmation_message'])) {
    echo '<div class="confirmation-message">' . $_SESSION['confirmation_message'] . '</div>';
    unset($_SESSION['confirmation_message']); // Supprimez le message de la session après l'affichage
}
?>
<h1>Conduisez-nous vers votre satisfaction !</h1>
<blockquote>
    <p>
        &laquo;Avant de soumettre votre message, nous tenons
        à vous rassurer que chaque demande est importante pour nous. 
        Nous nous engageons à vous répondre dans les meilleurs délais.&raquo;
    </p>
</blockquote>

<form action="/projet-final-v2/create_message" method="post" enctype="multipart/form-data">
    <input type="hidden" name="form-name" id="form-name" value="create-message">
    
    <fieldset>
        <label for="subject">Indiquer le sujet de votre message ici !</label>
        <input type="text" id="subject" name="subject" required>
    </fieldset>
    
    <fieldset>
        <label for="message_body">Votre message !</label>
        <textarea id="message_body" name="message_body" rows="5" required></textarea>
    </fieldset>
    <fieldset>
        <label for="fichiers">Ajouter des fichiers (PDF, JPG, PNG) :</label>
        <input type="file" id="fichiers" name="fichiers[]" accept=".pdf,.jpg,.png" multiple>    </fieldset>
    <fieldset>
        <input type="submit" value="Créer">
    </fieldset>
    <a href="/projet-final-v2/homepage">Retour à l'accueil</a>
</form>


</main>
