<h1>Êtes-vous sûr de vouloir supprimer cet utilisateur?</h1>
<p>
    Name: <?= $user['first_name'] ?> <?= $user['last_name'] ?><br>
    Email: <?= $user['email'] ?>
</p>
<form action="/projet-final-v2/admin/delete_user&id=<?= $user['User_ID'] ?>" method="post">
    <input type="hidden" name="confirm_delete" value="1">
    <button type="submit">Oui, Supprime</button>
</form>
<a href="/projet-final-v2/users">Non, Reviens en arrière</a>