<main id="editUser">

<h1>Modifier un utilisateur</h1>
<form action="/projet-final-v2/edit_user?id=<?= $user->getId() ?>" method="post">
    <fieldset>
    <label for="email">Email:</label>
    <input type="email" name="email" id="email" value="<?= $user->getEmail() ?>" required>
    </fieldset>
    <fieldset>
    <label for="first_name">Prénom:</label>
    <input type="text" name="first_name" id="first_name" value="<?= $user->getFirst_name() ?>" required>
    </fieldset>
    <fieldset>
    <label for="last_name">Nom:</label>
    <input type="text" name="last_name" id="last_name" value="<?= $user->getLast_name() ?>" required>
     </fieldset>
     <fieldset>
    <label for="role">Role:</label>
    <select name="role" id="role">
        <option value="user" <?= $user->getRole()->getRoleName() == 'user' ? 'selected' : '' ?>>User</option>
        <option value="admin" <?= $user->getRole()->getRoleName() == 'admin' ? 'selected' : '' ?>>Admin</option>
        <!-- Add more roles if needed -->
    </select>
    </fieldset>
    <fieldset>
    <input type="submit" value="Modifier">
    </fieldset>
</form>
</main>