
<main id="messagesEdit">
<h1>Éditer le Message</h1>
<form action="index.php?route=update_message&id=<?= $message['Message_ID']; ?>" method="post">
    <fieldset>
        <label for="subject">Sujet:</label>
        <input type="text" id="subject" name="subject" value="<?= $message['Subject']; ?>" required>
    </fieldset>
    <fieldset>
        <label for="message_body">Message:</label>
        <textarea id="message_body" name="message_body" rows="5" required><?= $message['Message_body']; ?></textarea>
    </fieldset>
    <fieldset>
        <input type="submit" value="Mettre à jour">
    </fieldset>
</form>
</main>
<a href="index.php?route=index_message">Retour à la liste des messages</a>
