<h1>Éditer le Message</h1>
<form action="index.php?route=update_message&id=<?= $message['Message_ID']; ?>" method="post">
    <label for="subject">Sujet:</label>
    <input type="text" id="subject" name="subject" value="<?= $message['Subject']; ?>" required>
    <br>
    <label for="message_body">Message:</label>
    <textarea id="message_body" name="message_body" rows="5" required><?= $message['Message_body']; ?></textarea>
    <br>
    <input type="submit" value="Mettre à jour">
</form>
<a href="index.php?route=index_message">Retour à la liste des messages</a>