<h1>Liste des Messages</h1>
<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Sujet</th>
            <th>Message</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($messages as $message) : ?>
            <tr>
                <td><?= $message['Message_ID']; ?></td>
                <td><?= $message['Subject']; ?></td>
                <td><?= $message['Message_body']; ?></td>
                <td>
                    <a href="index.php?route=view_message&id=<?= $message['Message_ID']; ?>">Voir</a>
                    <a href="index.php?route=edit_message&id=<?= $message['Message_ID']; ?>">Éditer</a>
                    <a href="index.php?route=delete_message&id=<?= $message['Message_ID']; ?>">Supprimer</a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<a href="index.php?route=create_message">Créer un nouveau message</a>