<main id="messageslist">
<h1>Liste des Messages</h1>
<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>User ID</th>
            <th>Subject</th>
            <th>Date</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <!-- Use PHP to loop through the messages and print their details -->
        <?php foreach ($messages as $message) : ?>
            <tr>
                <td><?= $message['Message_ID'] ?></td>
                <td><?= $message['User_ID'] ?></td>
                <td><?= $message['Subject'] ?></td>
                <td><?= $message['Message_datetime'] ?></td>
                <td>
                    <a href="/projet-final-v2/view_message&id=<?= $message['Message_ID'] ?>">Voir</a>
                    <a href="/projet-final-v2/messages&id=<?= $message['Message_ID'] ?>">Supprimer</a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
</main>
<script type="text/javascript" src="assets/js/listeMessages.js"></script>