<main id="updateProfil">
    <section class="container-profil">
    <?php if (isset($_SESSION['message'])): ?>
        <div class="message">
            <?= $_SESSION['message'] ?>
        </div>
        <?php unset($_SESSION['message']); ?>
    <?php endif; ?>
<h1>Modifier votre profil</h1>
<h2>Profil de : <span> <?= $user->getFirst_name() ?> <?= $user->getLast_name() ?></span></h2>
<form action="/projet-final-v2/update_profile" method="post">
    <fieldset>
        <label for="first_name">Nom:</label>
        <input type="text" id="first_name" name="first_name" value="<?= $user->getFirst_name() ?>">
    </fieldset>
    <fieldset>
        <label for="last_name">Prénom:</label>
        <input type="text" id="last_name" name="last_name" value="<?= $user->getLast_name() ?>">
    </fieldset>
    <fieldset>
        <label for="email">Email:</label>
        <input type="email" id="email" name="email" value="<?= $user->getEmail() ?>">
    </fieldset>
    <fieldset>
        <input type="submit" value="Mettre à jour">
    </fieldset>
</form>
</section>
</main>