<!DOCTYPE html>
<html>

<head>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta property="og:locale" content="fr_FR">
    <meta name="referrer" content="origin">
    <meta name="description" content="Votre Centre de Contrôle Technique agréé vous propose des contrôles rapides et fiables pour tous types de véhicules. Prenez rendez-vous en ligne dès maintenant.">
    <meta name="author" content="Tessier">
    <title>Drive Safe Controle privé</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <link rel="stylesheet" href="assets/styles/css/main.css">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@400&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lexend:wght@400&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@400&display=swap" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11" defer></script>
    <script src='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.8/index.global.min.js' defer></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.4/moment.min.js" defer></script>
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
</head>

<body>
    <nav>
        <?php
                // Gestion de l'accès en fonction du rôle utilisateur (admin, user, visiteur)
            if (isset($_SESSION["user_id"], $_SESSION["role"])) 
        {
            if ($_SESSION["role"] === "admin") 
            {
                require 'partials/header_admin.phtml';
            } else //* accès users
            {
                require 'partials/header_user.phtml';
            }
        } else //* accès visiteurs
        {
            require 'partials/header_visitor.phtml';
        }
        ?>
    </nav>
    <?php
    require $template;// Inclusion du template en fonction de la page
    ?>
    
   
    <footer>
        <?php
           // Gestion du footer en fonction du rôle utilisateur (admin, user, visiteur)
            if (isset($_SESSION["user_id"], $_SESSION["role"])) {
            if ($_SESSION["role"] === "admin") {
                require 'partials/footer_admin.phtml';
            } else {
                require 'partials/footer_user.phtml';
            }
        } else {
            require 'partials/footer_visitor.phtml';
        }
        ?>
    </footer>

</body>


</html>