<!DOCTYPE html>
<html>

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <title>Drive Safe Controle privé</title>
    <link rel="stylesheet" href="assets/styles/css/style.css">

</head>

<body>
    <nav>
        <?php
        if (isset($_SESSION["user_id"], $_SESSION["role"])) //* Control des variables de sessions pour l'acces users et admin
        {
            if ($_SESSION["role"] === "admin") //* Accès admin
            {
                require 'partials/header_admin.phtml';
            } else //* accès users
            {
                require 'partials/header_user.phtml';
            }
        } else //* accès visiteurs
        {
            require 'partials/header_visitor.phtml';
        }
        ?>
    </nav>
    <?php
    require $template;
    ?>
</body>


</html>