<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.8/index.global.min.js'></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.4/moment.min.js"></script>


<main id='planing-user'>
<h1>Pour réserver, sélectionnez un jour et un créneau ci-dessous.</h1>
<div id="calendar-container">
    <div id='calendar_user'></div>
</div>
</main>
<!-- Fichier JS pour le calendrier utilisateur -->
<script src="assets/js/calendarUser.js"></script>