<!-- Fichier views/calendar/calendar.phtml -->





<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.8/index.global.min.js'></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.4/moment.min.js"></script>
 <link rel="stylesheet" href="assets/style/css/calendar.css"> 




<

<div id='calendar-container'>
    <div id='calendar_admin'></div>
</div>


<script src="assets/js/calendar.js"></script>