<main id="register">
    <h2>Création de compte</h2>
    <form action="index.php?route=register" method="post">
        <p class="form-errors">
            <?php
            if (isset($data["errors"]))
                echo $data["errors"][0];
            ?>
        </p>
        <input type="hidden" name="form-name" id="form-name" value="register" />
        <fieldset>
            <label for="register-firstName">
                prénom
            </label>
            <input type="text" name="register-firstName" id="register-firstName" />
        </fieldset>
        <fieldset>
            <label for="register-lastName">
                nom
            </label>
            <input type="text" name="register-lastName" id="register-lastName" />
        </fieldset>
        <fieldset>
            <label for="register-email">
                Email
            </label>
            <input type="email" name="register-email" id="register-email" />
        </fieldset>
        <fieldset>
            <label for="register-password">
                Mot de passe
            </label>
            <input type="password" name="register-password" id="register-password" minlength="12" required />
        </fieldset>
        <fieldset>
            <label for="register-confirm-password">
                Confirmer le Mot de passe
            </label>
            <input type="password" name="register-confirm-password" id="register-confirm-password" minlength="12" required />
        </fieldset>
        <fieldset>
            <button type="submit">
                Créer un compte
            </button>
        </fieldset>
    </form>
    <?php if (isset($data['registered']) && $data['registered'] === true) : ?>
        <script>
            alert('Merci pour votre inscription ! Vous serez redirigé vers la page de connexion.');
            setTimeout(function() {
                window.location.href = 'index.php?route=login';
            }, 1000); // Redirection après 1 secondes
        </script>
    <?php endif; ?>
</main>