
<main id="homepage" >
    <!--<h1>Homepage </h1>-->
    
     <section id="slider-promo-section">
        <figure class="slider">
            <a href="/projet-final-v2/calendar_user" class="btn-appointment" >Prendre un rendez-vous</a>

                <img src="assets/images/femme-pouce-levé.jpg" alt="" class="img_slider active">
                <img src="assets/images/homme-controle-tablette.jpg" alt="" class="img_slider">
                <div class="suivant"><i class="fa-sharp fa-solid fa-circle-right"></i></div>
                <div class="precedent"><i class="fa-sharp fa-solid fa-circle-left"></i></div>
               <!-- Bouton pour prendre rendez-vous -->

        </figure>
        <aside id="promotions">
            <h2>Promotions Actuelles</h2>
            <!-- Votre code pour les promotions ici -->
        </aside>
    </section>
    
    <!-- Calendrier -->
    <section id="calendar-section">
        <!-- Votre code de calendrier ici -->
   
    </section>

    <!-- Horaires -->
    <article id="schedule-section">
        
    <table id="schedule-table">
        <thead>
            <tr>
                <th>Jour</th>
                <th>Heures d'ouverture</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Lundi</td>
                <td>8h00 - 18h00</td>
            </tr>
            <tr>
                <td>Mardi</td>
                <td>8h00 - 18h00</td>
            </tr>
            <tr>
                <td>Mercredi</td>
                <td>8h00 - 18h00</td>
            </tr>
            <tr>
                <td>Jeudi</td>
                <td>8h00 - 18h00</td>
            </tr>
            <tr>
                <td>Vendredi</td>
                <td>8h00 - 18h00</td>
            </tr>
            <tr class="closed">
                <td>Samedi</td>
                <td>Fermé</td>
            </tr>
            <tr class="closed">
                <td>Dimanche</td>
                <td>Fermé</td>
            </tr>
        </tbody>
    </table>
    <address>
        <strong>Adresse:</strong> 123 Rue Fausse, Ville, Code Postal<br>
        <strong>Téléphone:</strong> +00 123 456 789<br>
        <strong>Email:</strong> email@faux.com
    </address>
    <div class="map-container">
           <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2669.2924184035996!2d-1.700159823885021!3d48.00806016016948!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x480f1f8822f2a4cd%3A0x441fdd0a972258b7!2sContr%C3%B4le%20technique%20Pont%20P%C3%A9an%20Diagnosur!5e0!3m2!1sfr!2sfr!4v1693817963456!5m2!1sfr!2sfr" width="100%" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>

 </div>
    </article>

    <!-- Slider et Promotions -->
   
</main>
 <script src="assets/js/homepage.js"></script>
