<main id="faq">
    
    
    
      <h1>Questions Fréquentes sur le Contrôle Technique</h1>

    <h2>Général</h2>

    <dl>
        <dt>Q: Qu'est-ce qu'un contrôle technique ?
       <button class="toggle-icon" aria-label="Toggle Answer"><i class="fa-solid fa-plus"></i></button></dt>
       <dd class="hidden">R: Le contrôle technique est un examen périodique obligatoire des véhicules pour vérifier leur bon état de fonctionnement et leur conformité aux normes de sécurité.</dd>

        <dt>Q: Est-ce que le contrôle technique est obligatoire ?
        <button class="toggle-icon" aria-label="Toggle Answer"><i class="fa-solid fa-plus"></i></button></dt>
        <dd class="hidden">R: Oui, le contrôle technique est obligatoire pour les véhicules particuliers et les utilitaires légers.</dd>
    </dl>

    <h2>Rendez-vous</h2>

    <dl>
        <dt>Q: Comment puis-je prendre un rendez-vous ?
        <button class="toggle-icon" aria-label="Toggle Answer"><i class="fa-solid fa-plus"></i></button></dt>
        <dd class="hidden">R: Vous pouvez prendre un rendez-vous en ligne sur notre site Web, ou en nous appelant directement.</dd>

        <dt>Q: Dois-je payer en avance pour prendre un rendez-vous ?
        <button class="toggle-icon" aria-label="Toggle Answer"><i class="fa-solid fa-plus"></i></button></dt>
        <dd class="hidden">R: Non, le paiement se fait généralement sur place après le contrôle.</dd>
    </dl>

    <h2>Tarifs et Paiement</h2>

    <dl>
        <dt>Q: Combien coûte un contrôle technique ?
        <button class="toggle-icon" aria-label="Toggle Answer"><i class="fa-solid fa-plus"></i></button></dt>
        <dd class="hidden">R: Le tarif dépend du type de véhicule. Consultez notre site Web ou appelez-nous pour des informations précises.</dd>

        <dt>Q: Quels moyens de paiement acceptez-vous ?
        <button class="toggle-icon" aria-label="Toggle Answer"><i class="fa-solid fa-plus"></i></button></dt>
        <dd class="hidden">R: Nous acceptons les paiements en espèces, par carte bancaire et par chèque.</dd>
    </dl>

    <h2>Pendant le Contrôle</h2>

    <dl>
        <dt>Q: Combien de temps dure un contrôle technique ?
        <button class="toggle-icon" aria-label="Toggle Answer"><i class="fa-solid fa-plus"></i></button></dt>
        <dd class="hidden"> Un contrôle standard dure environ 45 minutes.</dd>

        <dt>Q: Puis-je rester dans le véhicule pendant le contrôle ?
        <button class="toggle-icon" aria-label="Toggle Answer"><i class="fa-solid fa-plus"></i></button></dt>
        <dd class="hidden">R: Non, pour des raisons de sécurité, vous ne pouvez pas rester dans le véhicule pendant le contrôle.</dd>
    </dl>

    <h2>Après le Contrôle</h2>

    <dl>
        <dt>Q: Que se passe-t-il si mon véhicule échoue au contrôle ?
        <button class="toggle-icon" aria-label="Toggle Answer"><i class="fa-solid fa-plus"></i></button></dt>
        <dd class="hidden">R: Si votre véhicule échoue au contrôle, vous devrez faire les réparations nécessaires et repasser le contrôle.</dd>

        <dt>Q: Recevrai-je un certificat après le contrôle ?
        <button class="toggle-icon" aria-label="Toggle Answer"><i class="fa-solid fa-plus"></i></button></dt>
        <dd class="hidden">R: Oui, un certificat vous sera remis à l'issue du contrôle technique.</dd>
    </dl>

</main>